# Generated by Django 4.1.7 on 2023-03-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameplay', models.IntegerField()),
                ('music', models.IntegerField()),
                ('art', models.IntegerField()),
                ('story', models.IntegerField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
    ]
